version: '3'

volumes:
  cache_spotify:
  cache_spotify_system:
 
services:
  spotify:
    image: giof71/librespot:latest
    container_name: spotify
    restart: unless-stopped
    privileged: true
    command: /usr/bin/librespot
    volumes:
      - ./data/spotify/fifo:/tmp/fifo
      - cache_spotify:/data/cache
      - ./credentials/spotify:/user/config
    environment:
      - BACKEND=pipe
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=Aether
      - DEVICE_TYPE=speaker
      - DEVICE=/tmp/fifo/fifo
      - ENABLE_CACHE=y
      - ENABLE_SYSTEM_CACHE=y
      - DISABLE_DISCOVERY=y
      - ENABLE_VOLUME_NORMALISATION=y
#      - AUTOPLAY=y
#      - PASSTHROUGH=y
